### ISSUE TITLE
Add "Insights" page

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/.build#4]
Link out to core definitions for each of our issues

Web lit, Digital Inclusion, Privacy, Decentralization, Open innovation, etc

**Comment by OpenMatt** [comment]
@samanthaburton I've started a stub here and we can add to main nav once you're ready
http://mofo.build/insights/

**Comment by samanthaburton** [comment]
This is great - thanks Matt. Will update later this week!

**Comment by samanthaburton** [comment]
Updated! http://mofo.build/insights

**Comment by OpenMatt** [comment]
- added to main nav
